# Generated by Django 6.0.1 on 2026-01-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoliorImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Durability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hunger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeteorShowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Morale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stress_reactions', models.BooleanField(default=True)),
                ('sandbox_mode', models.BooleanField(default=False)),
                ('teleporters', models.BooleanField(default=False)),
                ('care_packages', models.BooleanField(default=True)),
                ('save_to_cloud', models.BooleanField(default=False)),
                ('preset', models.CharField(choices=[('survival', 'Survival'), ('no-sweat', 'No sweat')], default='survival', max_length=100)),
                ('asteroid_style', models.CharField(choices=[('classic', 'Classic'), ('spaced_out', 'Spaced Out'), ('the-lab', 'The Lab')], default='classic', max_length=100)),
                ('demolior_impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colony_manager.demoliorimpact')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.disease')),
                ('durability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.durability')),
                ('hunger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.hunger')),
                ('meteorshowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.meteorshowers')),
                ('morale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.morale')),
                ('radiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.radiation')),
                ('stress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.stress')),
            ],
        ),
        migrations.CreateModel(
            name='Planetoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_dupes', models.PositiveIntegerField(default=0)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.colony')),
            ],
        ),
    ]
