# Generated by Django 6.0.1 on 2026-01-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('supportable_dupes', models.PositiveIntegerField(default=0)),
                ('survivable_cycles', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DemoliorImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Durability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_of_decay', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hunger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kcal_required', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MeteorShowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Morale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stress_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.blueprint')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_manager.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='selected_foods',
            field=models.ManyToManyField(through='colony_manager.BlueprintFoods', to='food_manager.recipe'),
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stress_reactions', models.BooleanField(default=True)),
                ('sandbox_mode', models.BooleanField(default=False)),
                ('teleporters', models.BooleanField(default=False)),
                ('care_packages', models.BooleanField(default=True)),
                ('save_to_cloud', models.BooleanField(default=False)),
                ('preset', models.CharField(choices=[('survival', 'Survival'), ('no-sweat', 'No sweat')], default='survival', max_length=100)),
                ('asteroid_style', models.CharField(choices=[('classic', 'Classic'), ('spaced_out', 'Spaced Out'), ('the-lab', 'The Lab')], default='classic', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demolior_impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colony_manager.demoliorimpact')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.disease')),
                ('durability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.durability')),
                ('hunger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.hunger')),
                ('meteorshowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.meteorshowers')),
                ('morale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.morale')),
                ('radiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.radiation')),
                ('stress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.stress')),
            ],
        ),
        migrations.CreateModel(
            name='Planetoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dupe_population', models.PositiveIntegerField(default=0)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.colony')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='planetoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony_manager.planetoid'),
        ),
    ]
