# Generated by Django 6.0.1 on 2026-01-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colony_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planetoid",
            old_name="number_of_dupes",
            new_name="dupe_population",
        ),
    ]
