# Generated by Django 6.0.1 on 2026-01-20 06:05

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colony_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprint",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="colony",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="planetoid",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
