# Generated by Django 6.0.1 on 2026-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony_manager", "0003_colony_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="durability",
            name="rate_of_decay",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="hunger",
            name="kcal_required",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="stress",
            name="stress_rate",
            field=models.IntegerField(default=0),
        ),
    ]
