"""
Django settings for UtilitiesNotIncluded.
Generated by KutologoJM
for Django 5.x.x
"""

from pathlib import Path
from django.conf.global_settings import AUTH_USER_MODEL
from dotenv import load_dotenv
import dj_database_url
import os

load_dotenv()

# Defines project paths in the form: BASE_DIR / "subdir" due to settings now being a package, Inner project folder becomes the root dir
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root urls
ROOT_URLCONF = 'UtilitiesNotIncluded.urls'

# WSGI
WSGI_APPLICATION = 'UtilitiesNotIncluded.wsgi.application'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Project Env managed
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")

# Site Admins
ADMINS = [
    ("Site Owner", "UtilitiesNotIncluded-admin@jezrastudio.online")
]

# Application Definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    "whitenoise",
]

LOCAL_APPS = [
    "accounts.apps.AccountsConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# New Default User
AUTH_USER_MODEL = 'accounts.CustomUser'  # noqa

# Project Middleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Database

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL_PROD"),
        conn_max_age=600,
        ssl_require=True,
    )
}

# Templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # noqa
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # noqa
STATICFILES_DIRS = [
    BASE_DIR / "static",  # noqa
]

# Whitenoise config
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"