# Generated by Django 6.0 on 2025-12-25 10:36

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wiki_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("dlc_name", models.CharField(blank=True, max_length=100)),
                ("dlc_wiki_url", models.URLField(blank=True)),
                ("dlc_image_url", models.URLField(blank=True)),
                (
                    "food_quality",
                    models.CharField(
                        choices=[
                            ("grisly", "Grisly"),
                            ("terrible", "Terrible"),
                            ("poor", "Poor"),
                            ("standard", "Standard"),
                            ("good", "Good"),
                            ("great", "Great"),
                            ("superb", "Superb"),
                            ("ambrosial", "Ambrosial"),
                        ],
                        max_length=10,
                    ),
                ),
                ("spoil_time", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal_per_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal_gained", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
