# Generated by Django 6.0 on 2026-01-02 07:43

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItemDLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("wiki_url", models.URLField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="FoodItemSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wiki_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.CharField(max_length=10)),
                ("morale_impact", models.IntegerField()),
            ],
            options={
                "verbose_name": "Food Quality",
                "verbose_name_plural": "Food Qualities",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wiki_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("spoil_time", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal_per_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("food_gained", models.CharField(blank=True, max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("is_ingredient", models.BooleanField(default=False)),
                (
                    "dlc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_manager.fooditemdlc",
                    ),
                ),
                (
                    "food_quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_manager.foodquality",
                    ),
                ),
                (
                    "sources",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_manager.fooditemsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("required", "Required"), ("subst", "Substitutable")],
                        default="required",
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kcal", "Kcal"),
                            ("kg", "Kg"),
                            ("units", "Units"),
                            ("g", "Grams"),
                        ],
                        default="kcal",
                        max_length=10,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_in",
                        to="food_manager.recipe",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="food_manager.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Ingredient",
                "verbose_name_plural": "Recipe Ingredients",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_in",
                through="food_manager.RecipeIngredient",
                to="food_manager.recipe",
            ),
        ),
    ]
