# Generated by Django 6.0.1 on 2026-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditemdlc",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="foodquality",
            name="quality",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("recipe", "ingredient")},
        ),
    ]
