# Generated by Django 6.0 on 2025-12-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.CharField(max_length=10)),
                ("morale_impact", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Food Quality",
                "verbose_name_plural": "Food Qualities",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="food_quality",
        ),
        migrations.AddField(
            model_name="recipe",
            name="food_quality",
            field=models.ManyToManyField(blank=True, to="food_manager.foodquality"),
        ),
    ]
