# Generated by Django 6.0.1 on 2026-01-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_manager",
            "0002_alter_fooditemdlc_name_alter_foodquality_quality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="food_quality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_manager.foodquality",
            ),
        ),
    ]
