# Generated by Django 6.0 on 2025-12-26 00:58

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0002_foodquality_remove_recipe_food_quality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItemSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wiki_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="food_quality",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="kcal_gained",
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="sources",
            field=models.ManyToManyField(blank=True, to="food_manager.fooditemsource"),
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wiki_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("dlc_name", models.CharField(blank=True, max_length=100)),
                ("dlc_wiki_url", models.URLField(blank=True)),
                ("dlc_image_url", models.URLField(blank=True)),
                ("spoil_time", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal_per_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal_gained", models.CharField(blank=True, max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "food_quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredient_food_quality",
                        to="food_manager.foodquality",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, to="food_manager.fooditemsource"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("main", "Main"), ("alt", "Alternate")],
                        default="main",
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[("kcal", "Kcal"), ("kg", "Kg"), ("units", "Units")],
                        max_length=10,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_manager.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_manager.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Ingredient",
                "verbose_name_plural": "Recipe Ingredients",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="food_quality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_food_quality",
                to="food_manager.foodquality",
            ),
            preserve_default=False,
        ),
    ]
