# Generated by Django 6.0.1 on 2026-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0003_alter_recipe_food_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
