# Generated by Django 6.0 on 2025-12-26 02:08

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0003_fooditemsource_remove_recipe_food_quality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="kcal_gained",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="kcal_gained",
        ),
        migrations.AddField(
            model_name="fooditemsource",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="food_gained",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kcal", "Kcal"),
                    ("kg", "Kilograms"),
                    ("units", "Units"),
                    ("g", "Grams"),
                ],
                default="kcal",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="food_gained",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="food_manager.RecipeIngredient",
                to="food_manager.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kcal", "Kcal"),
                    ("kg", "Kilograms"),
                    ("units", "Units"),
                    ("g", "Grams"),
                ],
                default="kcal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="foodquality",
            name="morale_impact",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="dlc_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="food_quality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredient",
                to="food_manager.foodquality",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="dlc_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="food_quality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe",
                to="food_manager.foodquality",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_links",
                to="food_manager.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_links",
                to="food_manager.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kcal", "Kcal"),
                    ("kg", "Kg"),
                    ("units", "Units"),
                    ("g", "Grams"),
                ],
                default="kcal",
                max_length=10,
            ),
        ),
    ]
