# Generated by Django 6.0.1 on 2026-01-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0004_alter_recipe_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("num_of_duplicants", models.PositiveIntegerField(default=0)),
                ("survivable_cycles", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Colony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("difficulty", models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name="BlueprintFoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_manager.blueprint",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_manager.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blueprint",
            name="selected_foods",
            field=models.ManyToManyField(
                through="food_manager.BlueprintFoods", to="food_manager.recipe"
            ),
        ),
        migrations.AddField(
            model_name="blueprint",
            name="colony",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="food_manager.colony"
            ),
        ),
    ]
