# Generated by Django 6.0 on 2025-12-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0004_remove_ingredient_kcal_gained_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_in",
                to="food_manager.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="used_in",
                through="food_manager.RecipeIngredient",
                to="food_manager.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="food_manager.recipe",
            ),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
