# Generated by Django 6.0 on 2025-12-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0005_alter_recipeingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditemsource",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_ingredient",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_in",
                through="food_manager.RecipeIngredient",
                to="food_manager.recipe",
            ),
        ),
    ]
