# Generated by Django 6.0.1 on 2026-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_manager", "0005_blueprint_colony_blueprintfoods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colony",
            name="population",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
