# Generated by Django 6.0.1 on 2026-01-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony_manager", "0002_rename_number_of_dupes_planetoid_dupe_population"),
        ("food_manager", "0006_colony_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueprint",
            name="colony",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="colony_manager.colony"
            ),
        ),
        migrations.RenameField(
            model_name="blueprint",
            old_name="num_of_duplicants",
            new_name="supportable_dupes",
        ),
        migrations.DeleteModel(
            name="Colony",
        ),
    ]
