# Generated by Django 6.0 on 2025-12-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_manager",
            "0006_fooditemsource_description_recipe_is_ingredient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kcal", "Kcal"),
                    ("kg", "Kilograms"),
                    ("units", "Units"),
                    ("g", "Grams"),
                ],
                default="kcal",
                max_length=10,
            ),
        ),
    ]
